---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
allowCompoundWords: true
dictionaryDefinitions:
  - name: project-dictionary
    path: './config/cspell/dictionary.txt'
    addWords: true
dictionaries:
  - project-dictionary

  - typescript
  - html
  - css
  - node
  - softwareTerms
  - companies
  - en-gb
ignorePaths:
  - 'target/**'
  - 'config/cspell/*.txt'
  - 'node_modules'
  - 'yarn.lock'
